// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClaR-6bmZojLR5_5gIOnLC9eeIcEcqNyU',
    appId: '1:760475798687:web:c8d442160fe1de79c9a6aa',
    messagingSenderId: '760475798687',
    projectId: 'foodappfirebase-7a670',
    authDomain: 'foodappfirebase-7a670.firebaseapp.com',
    storageBucket: 'foodappfirebase-7a670.appspot.com',
    measurementId: 'G-S6F71V35XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8WNWsDceNmvu5xRi19-_-sTjQr7cUkns',
    appId: '1:760475798687:android:460fba0976d7e153c9a6aa',
    messagingSenderId: '760475798687',
    projectId: 'foodappfirebase-7a670',
    storageBucket: 'foodappfirebase-7a670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalvAmueN6MoOTdaKZ4WEqFdHseJLoDRE',
    appId: '1:760475798687:ios:a2abb4a6cb060c2ac9a6aa',
    messagingSenderId: '760475798687',
    projectId: 'foodappfirebase-7a670',
    storageBucket: 'foodappfirebase-7a670.appspot.com',
    iosBundleId: 'com.example.foodAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDalvAmueN6MoOTdaKZ4WEqFdHseJLoDRE',
    appId: '1:760475798687:ios:a2abb4a6cb060c2ac9a6aa',
    messagingSenderId: '760475798687',
    projectId: 'foodappfirebase-7a670',
    storageBucket: 'foodappfirebase-7a670.appspot.com',
    iosBundleId: 'com.example.foodAppFirebase',
  );
}
